### ISSUE TITLE
Multidimensional indexing

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/EndpointRanges.jl#3]
Nice package. I like how this works - however it seems that multidimensional indexing might be a bit trickier to work out.

Some options off the top of my head:

 * Let the user specify which dimension they mean. `mat[ibegin(1):iend(1), 3]`
 * Get deep into `getindex` so the indices can figure out which dimension they relate to.

**Comment by timholy** [comment]
Not quite sure what you found to be broken, but certainly as of #13 multidim seems to be working as I'd expect.
